# SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

on:
  workflow_dispatch: {}

jobs:
  osv-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup AMPEL   
        uses: carabiner-dev/actions/install/ampel@HEAD
  
      - name: "Run scanner"
        uses: google/osv-scanner-action/osv-scanner-action@119c605e0e6e6c491e092da25b0c752d109b0b43 # v2.0.0
        continue-on-error: true
        with:
          scan-args: |-
            --output=osv-results.json 
            --format=json
            .
      - name: Verify Branch Policy
        run: |
            ampel verify \
              --subject=sha256:34c392aa1a59b8713996177675c06aa43379694015194d84d7050caea21562e3 \
              --policy policy/CRA-AI-2.a-XFORM.ampel.json \
              --attestation osv-results.json \
              --format=markdown >> $GITHUB_STEP_SUMMARY
      # - name: Print scan
      #   run: |
      #     cat osv-results.json
